// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/register": {
    params: {};
  };
  "/play": {
    params: {};
  };
  "/admin": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/login" | "/register" | "/play" | "/admin";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/auth/login.tsx": {
    id: "routes/auth/login";
    page: "/login";
  };
  "routes/auth/register.tsx": {
    id: "routes/auth/register";
    page: "/register";
  };
  "routes/layouts/AuthenticatedRoute.tsx": {
    id: "routes/layouts/AuthenticatedRoute";
    page: "/play" | "/admin";
  };
  "routes/quiz/play.tsx": {
    id: "routes/quiz/play";
    page: "/play";
  };
  "routes/layouts/AdminRoute.tsx": {
    id: "routes/layouts/AdminRoute";
    page: "/admin";
  };
  "routes/admin.tsx": {
    id: "routes/admin";
    page: "/admin";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/auth/login": typeof import("./app/routes/auth/login.tsx");
  "routes/auth/register": typeof import("./app/routes/auth/register.tsx");
  "routes/layouts/AuthenticatedRoute": typeof import("./app/routes/layouts/AuthenticatedRoute.tsx");
  "routes/quiz/play": typeof import("./app/routes/quiz/play.tsx");
  "routes/layouts/AdminRoute": typeof import("./app/routes/layouts/AdminRoute.tsx");
  "routes/admin": typeof import("./app/routes/admin.tsx");
};